/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-29c35f18",
      "path": "/"
    },
    {
      "title": "卡片組件",
      "frontmatter": {},
      "regularPath": "/componentsDocs/card.html",
      "relativePath": "componentsDocs/card.md",
      "key": "v-0c91a8d8",
      "path": "/componentsDocs/card.html"
    },
    {
      "frontmatter": {
        "layout": "v-b5af2be6"
      },
      "regularPath": "/components/card.html",
      "relativePath": "components/card.vue",
      "key": "v-b5af2be6",
      "path": "/components/card.html"
    }
  ],
  "themeConfig": {
    "head": [
      [
        "link",
        {
          "rel": "icon",
          "href": "/logo.png"
        }
      ]
    ],
    "sidebar": [
      "/",
      "/componentsDocs/card"
    ]
  }
}